### ISSUE TITLE
missing index.html in v5/app

### ISSUE THREAD

**Issue by ivanistheone** [savarin/minimal#2]
upon running `wasm-pack build --target web --out-name wasm --out-dir ./static` in `minimal/v5/app` there is no index.html generated in static/:

```
minimal/v5/app> tree static/
static/
├── package.json
├── wasm.d.ts
├── wasm.js
├── wasm_bg.d.ts
└── wasm_bg.wasm
```

**Comment by savarin** [comment]
Discussed offline. It's unclear if this is a one-off from dependencies, will close for now and review if re-occurs.
